export const AUTHENTICATE = "AUTHENTICATE";
export const DEAUTHENTICATE = "DEAUTHENTICATE";
export const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED";
export const USER_INFO = "USER_INFO";
export const USER_INFO_FAILED = "USER_INFO_FAILED";
